name: 3-Test - Build-Deploy # Nom du Workflow
on:
  workflow_dispatch # Déclenchement manuel

env:
  RG_NAME: "RG-AKS-0007"
  CLUSTER_NAME: "AKS-00001"
  ACR_NAME: "acraks00001"
  IMAGE_NAME: "azure-vote-front"
  NAMESPACES: "democatdog00"


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo Workflow "Build_Deploy.yml"

    # Step 1
    #- name: Récupération du repo.
    #  uses:  #Vérifie le dépôt sous $GITHUB_WORKSPACE, afin que les jobs puisse y accéder

    # Step 2
    # Action "Login Azure" # Marketplace 'GitHubAction' https://github.com/marketplace/actions/azure-login


    # Step 3
    # Récupération des clés de l'Azure Container Registry
    #- name: Get Key ACR
    #  run: |
    #    key=`az acr credential show --resource-group ${{ env.RG_NAME }} --name ${{ env.ACR_NAME}} --query passwords[0].value --output tsv`
    #    echo "::set-output name=content::$key"
    #  id: var_acrkey        


    # Step 4
    # Connexion à Azure Container Registry "https://github.com/marketplace/actions/azure-container-registry-login"
    # Pour le password, mettre "${{ steps.var_acrkey.outputs.content }}" 


    # Step 5 Build & Push
    # Pour la version de l'image mettre ${{ github.sha }}
    #- name: Build & Push
    #  run: |
    #    cd Src && docker build . -t ........
    #    docker push .......


  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:

    - run: |
        echo Workflow "Build_Deploy.yml"    

    # Step 1
    #- name: Récupération du repo.
    #  uses:  #Vérifie le dépôt sous $GITHUB_WORKSPACE, afin que les jobs puisse y accéder

    # Step 2
    # Action "Login Azure" # Marketplace 'GitHubAction' https://github.com/marketplace/actions/azure-login

    # Step 3
    # Récupération des clés de l'Azure Container Registry

    # Step 4
    # Connexion à Azure Container Registry "https://github.com/marketplace/actions/azure-container-registry-login"

    # Step 5
    # Context https://github.com/marketplace/actions/azure-kubernetes-set-context
    
    # Step 6
    # Deploiement de l'application
    #https://github.com/marketplace/actions/deploy-to-kubernetes-cluster