name: 4-Test - Push-Build-Deploy # Nom du Workflow 
on:
  workflow_dispatch # Déclenchement manuel
  #Exercice . Faire un déclenchement du Workflow sur un push lors d'une modification dans le repertoire /Src

env:
  RG_NAME: "RG-AKS-0007"
  CLUSTER_NAME: "AKS-00001"
  ACR_NAME: "acraks00001"
  IMAGE_NAME: "azure-vote-front"
  NAMESPACES: "democatdog01" # modifier le fichier manifest en "democatdog01" /Src/azure-vote-all-in-one-redis.yaml & ajouter <h1>democatdog01</h1> /Src/azure-vote/templates/index.html


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo Workflow "Build_Deploy.yml"


  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:

    - run: |
        echo Workflow "Build_Deploy.yml"